### ISSUE TITLE
[Feature]: new soup weegee u

### ISSUE THREAD

**Issue by SpareEnderboy** [PretendoNetwork/miiverse-api#38]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What feature do you want to see added?

New Super Luigi U Miiverse posting functionality

### Why do you want to have this feature?

NSLU already allowed posting to miiverse (found out on a stream lol) but it didn't work on the stream. The streamer has been confirmed by me to be using pretendo.

**Comment by ItzSwirlz** [comment]
There are several roadblocks, but the current super-mario-3d-world-authentication and super-mario-3d-world-server implementation work - technically.

First, there needs to be a Juxt community for SM3DW. But what's weird is at least with the USA version, the title id had to be `1407375153323008`?

Second, it currently as of writing/debugging: Communities need the `minimum_new_post_access_level` field to be implemented.

**Comment by TraceEntertains** [comment]
NSLU/NSMBU will probably exist At Some Point:tm:, but not created yet, but the appdata field (the thing telling the game the right community for NSLU/NSMBU) has previously been reverse engineered (by me actually!) so it shouldn't be too big of an issue adding support.

**Comment by jonbarrow** [comment]
These issues shouldn't be used to request communities (at least not for communities which are assumed to be coming eventually), nor should it be used for asking for specific games to be supported

You should assume that all games will be supported eventually, and that with those games will come the proper communities. This issue tracker should be used for reporting bugs and requesting *new* features
