### ISSUE TITLE
[Feature]: Miiverse Web

### ISSUE THREAD

**Issue by Santabo** [PretendoNetwork/miiverse-api#40]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What feature do you want to see added?

Miiverse implemented into a normal web browser so you can access just by logging into pretendo on browser.

### Why do you want to have this feature?

I would find it easier to access miiverse as I have it on my Wii U and don't have a portable 3DS, it would also be easier to scroll on web too.

**Comment by superfever3000** [comment]
pretendo already has a juxt/miiverse client for the web https://juxt.pretendo.network

**Comment by jonbarrow** [comment]
As stated, this is already a thing
